In [1]:
import pandas as pd
import numpy as np

In [3]:
from sentence_transformers import SentenceTransformer, util
resume_df = pd.read_csv('../data/archive/Resume/Resume.csv')
jobs_df = pd.read_csv("../data/archive/job_title_des.csv")

model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [6]:
resume_df.head(5)

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [7]:
jobs_df.head(5)

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n..."
3,3,iOS Developer,JOB DESCRIPTION:\n\nStrong framework outside o...
4,4,Full Stack Developer,job responsibility full stack engineer – react...

In [8]:
resume_text = resume_df['Resume_str'].iloc[0]
job_text = jobs_df['Job Description'].iloc[0]

resume_embedding = model.encode(resume_text)
job_embedding = model.encode(job_text)

similarity_score = util.cos_sim(resume_embedding, job_embedding)

print(f"Resume Category: {resume_df['Category'].iloc[0]}")
print(f"Job Title: {jobs_df['Job Title'].iloc[0]}")
print(f"Similarity Score: {similarity_score.item():.2f}")

Resume Category: HR
Job Title: Flutter Developer
Similarity Score: 0.25

In [9]:
it_resume = resume_df[resume_df['Category'] == 'INFORMATION-TECHNOLOGY']
resume_text2 = it_resume['Resume_str'].iloc[0]
resume_embedding_it = model.encode(resume_text2)
similarity_score_2 = util.cos_sim(resume_embedding_it, job_embedding)
print(f"Resume Category: IT")
print(f"Job Title: {jobs_df['Job Title'].iloc[0]}")
print(f"Similarity Score: {similarity_score_2.item():.2f}")

Resume Category: IT
Job Title: Flutter Developer
Similarity Score: 0.15

In [11]:
print(it_resume['Resume_str'].iloc[0][:500])

         INFORMATION TECHNOLOGY         Summary     Dedicated  Information Assurance Professional  well-versed in analyzing and mitigating risk and finding cost-effective solutions. Excels at boosting performance and productivity by establishing realistic goals and enforcing deadlines.  Versatile IT professional with 37 years of Enterprise design and engineering methodology.       Skills          Enterprise platforms  Knowledge of Product Lifecycle Management (PLM)  Project tracking  Hardware an

In [12]:
dev_resume = it_resume[it_resume['Resume_str'].str.contains('developer|programming|software', case=False, na=False)]
print(len(dev_resume))
print(dev_resume['Resume_str'].iloc[0][:300])

106
         INFORMATION TECHNOLOGY         Summary     Dedicated  Information Assurance Professional  well-versed in analyzing and mitigating risk and finding cost-effective solutions. Excels at boosting performance and productivity by establishing realistic goals and enforcing deadlines.  Versatile IT

In [13]:
print(dev_resume['Resume_str'].iloc[5][:300])

         INFORMATION TECHNOLOGY AUDITOR         Skills        PeopleSoft HCM 8.8/9.x, PeopleSoft Financials 8.8/9.x,  PeopleTools 8.51/ 8.54, SQL Developer, MS Office, Visio, MS Project, Dell Stat 5.6/5.7, SQL Developer, Application Designer, Putty, SharePoint, HP Application Lifecycle Management, O

In [14]:
dev_resumes_list = dev_resume['Resume_str'].tolist()
dev_embeddings = model.encode(dev_resumes_list)

scores = util.cos_sim(dev_embeddings, job_embedding)

best_idx = scores.argmax().item()
print(f"Best match score: {scores[best_idx].item():.2f}")
print(dev_resumes_list[best_idx][:400])

Best match score: 0.51
         FREELANCE IT CONSULTANT       Career Overview    Highly skilled, results-driven Information Technology Specialist/Consultant with experience in business operations, infrastructure management, software/hardware support, high/low end PC and Microsoft Server administration, and software development. Core Strengths Excellent critical and analytical skills		Business process management Superior